### ISSUE TITLE
Custom configuration does not work

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-nethermind#73]
**Describe the bug**

If you try to install the package and select the custom installation where you have to upload a custom file, the package does not install correctly.

**To Reproduce**

Error: No service for nethermind.public.dappnode.eth
    at /usr/src/app/webpack:/@dappnode/dappmanager/src/modules/installer/runPackages.ts:65:31
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:278064:58)
```
Call to packageInstall
Reply: No service for nethermind.public.dappnode.eth
{
  "name": "nethermind.public.dappnode.eth",
  "version": "/ipfs/QmSuN1hVirwVFj6zCpoy1gVcXx7eA9fqiXLvNsdPMH3Fdt",
  "userSettings": {
    "nethermind.public.dappnode.eth": {
      "environment": {
        "nethermind.public.dappnode.eth": {
          "MODE": "custom"
        }
      },
      "fileUploads": {
        "nethermind.public.dappnode.eth": {
          "/data/custom.cfg": "data:application/octet-stream;name=custom.cfg"
        }
      }
    }
  },
  "options": {
    "BYPASS_SIGNED_RESTRICTION": true
  }
}
```

**Expected behaviour**

The package should be installed with this custom file.

**Additional context**

There is a typo error in the setup-wizard where two variables have the same ID's 
`UseGethLimitsInFastBlocks` but even changing this value, the error persists.

**Comment by dapplion** [comment]
Should be fixed by reverting the service name change
